### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earthlab.github.io#14]
We need to get this bad boy under some kind of CI so we can avoid breaking stuff. I think there are different levels that we could consider:

- [x] Level 0: does the site build?
- [ ] Level 1: can we generate md files from Rmd and Jupyter notebooks, then build the site?

I think we can implement these sequentially - and the level 0 might be a good way to make sure that nothing goes awry while I work on level 1.

**Comment by lwasser** [comment]
@mbjoseph do you think we got this bad boy under control so we can close this now? we aren't building my lessons yet but everything else is building. yea?

**Comment by mbjoseph** [comment]
Sure thing. If at some point you want to build your lessons as part of the make workflow, we can do that as a separate issue!

**Comment by lwasser** [comment]
I do. My build process is terrible now. I’d really like to sit down with you sometime to talk about it because


1.       I need to improve my knitr script. And I know you can help guide me

2.       I have a zillion lessons to build and I’m building each set individually.

Maybe after the furniture move we can chat sometime?

**Comment by mbjoseph** [comment]
Ok let's plan to touch base after the new furniture arrives.
