### ISSUE TITLE
support a bio on the authors page

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#18]
_From @lwasser on October 26, 2016 22:46_

Following - issue https://github.com/earthlab/dev-earthlab-site/issues/5 , we may want to add a short bio to each author page. This bio could be stored in a csv file which maps the author slug to an excerpt bio which then gets written to each bio page in the make file. This is future functionality, not stuff we need immediately. 

_Copied from original issue: earthlab/dev-earthlab-site#16_

**Comment by lwasser** [comment]
- [x] leah will create the csv and place into the `_data` dir w headings slug, content
- [ ] @mbjoseph will add code to the workflow to scan the csv for the slug, and add the bio text.

**Comment by lwasser** [comment]
@mbjoseph  the csv is here -- https://github.com/earthlab/earthlab.github.io/blob/dev/org/author-bios.csv it breaks the site in the data dir.

**Comment by mbjoseph** [comment]
Ok, the bios are now included in the authors org pages with 2efd466ebc4372d2c75b5a35fee46a168e15d16b. Next step I think is modifying the post-by-author layout so that the bio text shows up?

**Comment by lwasser** [comment]
Oh cool - i wasn't expecting you to do it that way BUT that works. Yes adding the bios is easy. i'll assign this back to myself.

**Comment by lwasser** [comment]
@mbjoseph aren't we pushing to dev first then master? is this on master?  please clarify.

**Comment by mbjoseph** [comment]
I would push to a new branch with a good name rather than 'dev' by default, with each branch representing one coherent collection of changes. So here you could commit to a branch called feature/include-author-bios, then submit a pull request. 

Pushing to master is a bad idea in general, compared to submitting a PR, since we cannot know ahead of time whether the changes will break our build. With a PR, we get to see the build before merging with master.

**Comment by lwasser** [comment]
That makes sense but -- we are pushing from each branch to master rather than each branch --> dev (representing all current edits for testing) --> master ?

I suppose I thought we were immolating a dev environment here with a dev branch? Right now dev is behind because you pushed stuff to master from another branch.

**Comment by mbjoseph** [comment]
I think that's a decision that we should make together. My preference would be to keep all changes for a new thing on one branch, and then open pull requests to merge these into master. I like the feature branch -> master branch model because each pull request represents a relatively small set of changes that should be easy to review. 

If we instead go with feature -> dev -> master, then merging dev with master represents a larger, more heterogeneous set of changes which will be harder to review.

**Comment by mbjoseph** [comment]
Also, happy to chat offline if that's easier! Maybe we should also think about putting together a `CONTRIBUTING.md` file that let's other people know what our process is.

**Comment by lwasser** [comment]
Let’s chat in person.

I think your approach works if the changes are small and quick. But – for instance I’m working on things maybe for months. If there are changes on other branches – do I just do PR’s from master then to test integration? How do you test how your edits conflict or not with my edits?  I just need to understand the workflow and all will be fine!

**Comment by lwasser** [comment]
@mbjoseph i think we've covered this at this point - (except for the contributing file). what do you think? Can we close it?

**Comment by mbjoseph** [comment]
I think so - any other technical issues that come up can probably be safely opened as new issues.
