### ISSUE TITLE
Week_10

### ISSUE THREAD

**Issue by SepidehD** [earthlab/earthlab.github.io#230]
@lwasser 
- [x] it should be week 10 instead of week 8?
![image](https://cloud.githubusercontent.com/assets/16745365/24912050/38c920d8-1e8a-11e7-8d6e-babbf104a274.png)

- [ ] The last sentence is true?
![image](https://cloud.githubusercontent.com/assets/16745365/24912310/f775e2aa-1e8a-11e7-823a-535f9d562f82.png)

- [x] then we work with the?
![image](https://cloud.githubusercontent.com/assets/16745365/24915667/05cfd306-1e95-11e7-9a9a-3b9b61f546fe.png)
https://earthlab.github.io/course-materials/earth-analytics/week-10/intro-to-programmatic-data-access-r/

**Comment by lwasser** [comment]
Good catch! I'm having a few Internet issues. Once resolved I'll fix this!! Thank you!!!

Leah A. Wasser
---
Director, Earth Analytics Education Initiative
Earth Lab, CU Boulder
twitter: @leahawasser


________________________________

**Comment by lwasser** [comment]
hey @SepidehD thank you! i do want them to show us their code this week because we want to see how they are getting their data. it will be easier to grade that way!!

I fixed the landing page typos and the lesson typos. the landing page typos will be live now or soon but the other typos won't be live until i push a huge new set of edits live to the website. i didn't want to do that while the students are working on things!! SO i'll update that typo tomorrow. Great catch!! 
welcome back!

**Comment by SepidehD** [comment]
- [ ]  The last sentence is not very clear for me.
![image](https://cloud.githubusercontent.com/assets/16745365/24916417/535d0a6a-1e97-11e7-8bab-e4121a158997.png)
https://earthlab.github.io/course-materials/earth-analytics/week-10/intro-to-programmatic-data-access-r/
Thank you Leah!
I am reading the materials since I have office hours today.
I will keep posting if I found other issues.

See you soon.
Sepideh

**Comment by lwasser** [comment]
Great! i can tell you more tomorrow @SepidehD I had to redo a lot of the lessons because some of the code was wrong. it was right last year when Carson taught it but things have changed! However i wanted to be careful about changing things the day before the lesson is due SO -- i'll totally make all of the edits that ou find today BUT won't push them until tomorrow at noon. Thanks again.

no one came to my office hours yesterday. the homework is pretty short. the extra credit is a bit hard if they do the second extra credit however. you can see the code hidden in the .RMD document if you want to see the answers!

**Comment by SepidehD** [comment]
- [ ]  the x axis should not be year?
![image](https://cloud.githubusercontent.com/assets/16745365/24920137/60f1dd2a-1ea3-11e7-95f7-0f5d3c13d50b.png)

https://earthlab.github.io/course-materials/earth-analytics/week-10/access-gapminder-data-rcurl-r/

**Comment by SepidehD** [comment]
@lwasser 
in assignment, at the top you asked for submitting html and rmd. At the end, you asked for pdf and rmd.

now, I am looking to submitted assignments. The html files contain just codes, it doesnt show the plots.
is there any way to see the plots in html?

Sepideh

**Comment by lwasser** [comment]
Yes – we talked about this. If you download all of the assignments to your computer, you can see the plots.they are only masked online in d2l.

If they selected pdf the leaflet map won’t plot. So that is why I asked for HTML.

**Comment by SepidehD** [comment]
thank you.

I see.
Sepideh


*- - - - - - - - - - - - - - - - - - Sepideh Dadashi*
Graduate Student and Research Assistant
University of Colorado at Boulder

**Comment by lwasser** [comment]
I just fixed the pdf vs html thing so it was consistent. Thank you for catching that inconsistency. But I’m ok if they submit pdf’s – its just that it won’t work with leaflet so if they don’t do the bonus point, a pdf is just fine. However html is preferred.

**Comment by lwasser** [comment]
ok @SepidehD all of the edits above should be live. please close this unless there is anything else that you caught that needs to be fixed! i do want the students to show their code this week so that part of the assignment is just fine. everything else i fixed (i think!)

**Comment by lwasser** [comment]
Closing this as i've made all of these changes!!
