### ISSUE TITLE
Granularity of file-formats

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#268]
hey @mbjoseph i just realized that the file-formats element could get really crazy quickly

```
file-formats: 
    subtopics: ['hdf5', 'json', 'csv', 'raster',  'shapefile', 'geotiff']
```
I'm thinking H5, h4, netcdf, all of the 8 billion text formats. JSON, Geojson, etc etc

i wondered if we wanted slightly more general bins like

Hierarchical-data-format-hdf 
network-common-data-form-netCDF 
text-files  <- csv, txt, etc all here
structured-data <- xml, json etc 

i keep going back and forth on whether we need an explicit landing page for say the geotiff format - we may still have a page on it but an entire section on it? 

Thoughts?

**Comment by mbjoseph** [comment]
Good point - my preference would be to include all of the file formats as subtopics as we currently do, because we only have to maintain `_data/topics.yml`. I would also guess that people are going to search for the specific file formats that they are working with, rather than a more general version, e.g., "How to XYZ a JSON file" rather than "How to XYZ a structured data file".

**Comment by lwasser** [comment]
Ok! so let's leave it as is then! i'll close this issue and will move this back to the other issue that is almost closed. Thanks @mbjoseph !!
