### ISSUE TITLE
Check internal links agains generated site, not deployed site

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earthlab.github.io#293]
From @lwasser:

The problem is that if the live site doesn’t have the md page travis fails. The config file is now testing against the live site Can we fix this? It’s going to be an ongoing issue. Can we force travis to use a config without the url so it builds a local version and doesn’t test against the live site?

**Comment by lwasser** [comment]
Note: this file 
https://github.com/earthlab/earthlab.github.io/blob/master/_config.yml
is where the site.url is populated from. 

Specifically this line

`url  : "http://earthdatascience.org"`
needs to be commented out when you build locally to ensure you're doing a fully local test rather than testing againsted the live site like so:

`url  :  #"http://earthdatascience.org"`
When the url is commented out, a local build will be successful. Travis could also be successful via this config file modification for it's build.

**Comment by mbjoseph** [comment]
Maybe we can also have a dev _config.yml file instead of having to modify the existing one? https://mademistakes.com/articles/using-jekyll-2016/

**Comment by lwasser** [comment]
Oh – I just did a quick scan but how cool is this guy? That is the perfect solution if it works?!! This has been an ongoing issue for me for all of my Jekyll sites. Then you forget you’ve modified the config and ofcourse run into issues with the live site… cool!
