### ISSUE TITLE
mapply  /apply vs for loop

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthlab.github.io#81]
hey @mbjoseph i've been working on my knitr code. 

https://github.com/earthlab/earthlab.github.io/blob/dev-lessons/processing-code/knitRMD-2-MD-all-new-files.R

i noticed that you are using a for loop to process each lesson. Couldn't we do this / is it better to do this with mapply or do.call ? I am asking because i actually am having a hard time with getting mapply or do.call to work across a dataframe. If you have a few minutes to check it out, i'd love your input.

No rush or urgency, i'd just like to make my code better. I can always do a for loop too.

**Comment by mbjoseph** [comment]
Nice! This is looking better. I don't think we really need to bother with avoiding the loop unless we have a specific reason. If I'm working with a data frame I typically use dplyr::do() rather than do.call or mapply, but for now I'm ok with sticking to the loop. I could be convinced otherwise though.

**Comment by lwasser** [comment]
Ok. I’d like to understand how to use do.call and mapply so I suppose part of this is a learning opportunity for me ☺ I spent a while on it last night.

For now – I’ll loop through things ☺ when you have a few, could we chat about do() and mapply ?

I get how lists work but can’t wrap my head around the df approach.

**Comment by lwasser** [comment]
closing this issue for now!
